version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build .
  eslint:
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - node/install-packages
      - run: mkdir -p ~/reports
      - run: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
workflows:
  version: 2
  eslint:
    jobs:
      - eslint
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
